# Data Structure

In [ ]:
from scripts.mouse import Mouse

In [35]:
# This was a test to see if the session was being created correctly. Since the
# tests have passed, `Mouse().session` has been deleted to save memory.

# cori1 = Mouse(1)
# session = cori1.session
# assert all(session[0] == cori1.contrast_left)
# assert all(session[1] == cori1.contrast_right)
# assert all(session[2] == cori1.feedback_type)

## Structure of the `Mouse()` files.

```python
>>> for session in range(1, 19):
>>>     print(f"{session = }: {Mouse(session)}")
```
```powershell
session = 1: Cori on 12/14/2016
session = 2: Cori on 12/17/2016
session = 3: Cori on 12/18/2016
session = 4: Forssmann on 11/01/2017
session = 5: Forssmann on 11/02/2017
session = 6: Forssmann on 11/04/2017
session = 7: Forssmann on 11/05/2017
session = 8: Hench on 06/15/2017
session = 9: Hench on 06/16/2017
session = 10: Hench on 06/17/2017
session = 11: Hench on 06/18/2017
session = 12: Lederberg on 12/05/2017
session = 13: Lederberg on 12/06/2017
session = 14: Lederberg on 12/07/2017
session = 15: Lederberg on 12/08/2017
session = 16: Lederberg on 12/09/2017
session = 17: Lederberg on 12/10/2017
session = 18: Lederberg on 12/11/2017
```

## Testing the Data Pipelines

See `./scripts/open_rds.py` and `./scripts/mouse.py`

In [40]:
cori = [Mouse(i) for i in range(1, 4)]
forssmann = [Mouse(i) for i in range(4, 8)]
hench = [Mouse(i) for i in range(8, 12)]
lederberg = [Mouse(i) for i in range(12, 19)]

In [41]:
cori_trial_1 = cori[0]

# Test basic string representations

print(cori_trial_1)
print(cori_trial_1.mouse_name)
print(cori_trial_1.date_exp)

Cori on 12/14/2016
Cori
2016-12-14


In [10]:
cori_trial_1.feedback_type

array([ 1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,
       -1., -1., -1.,  1.,  1.,  1.,  1.,  1., -1., -1.,  1.,  1.,  1.,
        1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1., -1.,  1.,  1.,  1.,  1., -1.,  1., -1.,  1.,  1.,  1.,
       -1., -1.,  1.,  1., -1., -1., -1.,  1.,  1.,  1., -1., -1., -1.,
       -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,
        1., -1.,  1.,  1.,  1.,  1., -1.,  1., -1.,  1., -1., -1., -1.,
       -1.,  1., -1.,  1., -1.,  1.,  1.,  1., -1., -1., -1., -1.,  1.,
       -1.,  1.,  1., -1., -1., -1., -1., -1., -1., -1.])

In [11]:
cori_trial_1.contrast_left

array([0.  , 0.  , 0.5 , 0.  , 0.  , 0.  , 1.  , 0.5 , 0.  , 0.5 , 0.5 ,
       0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.5 , 0.25, 0.  , 1.  ,
       0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.5 , 0.  , 0.  ,
       0.5 , 0.  , 0.  , 0.  , 0.25, 0.  , 1.  , 0.  , 0.  , 1.  , 1.  ,
       0.5 , 1.  , 1.  , 0.  , 0.25, 0.25, 0.5 , 1.  , 0.25, 0.5 , 0.  ,
       0.  , 0.25, 0.25, 0.25, 0.  , 0.  , 0.  , 0.25, 0.25, 0.25, 0.25,
       0.25, 0.  , 0.5 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25,
       0.  , 1.  , 0.25, 0.  , 0.5 , 1.  , 1.  , 0.  , 1.  , 0.  , 0.5 ,
       0.25, 0.25, 0.25, 0.25, 0.5 , 0.5 , 1.  , 0.5 , 0.  , 0.25, 1.  ,
       0.25, 0.5 , 0.5 , 1.  , 1.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.  ,
       0.25, 0.25, 0.25, 0.25])

In [12]:
cori_trial_1.contrast_right

array([0.5 , 0.  , 1.  , 0.  , 0.  , 0.  , 0.5 , 0.  , 0.  , 0.25, 0.  ,
       1.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.5 , 0.25, 1.  , 0.  , 0.5 ,
       0.  , 0.  , 0.25, 0.25, 0.5 , 0.  , 0.  , 0.5 , 0.  , 0.  , 0.  ,
       0.5 , 0.25, 1.  , 0.5 , 1.  , 0.  , 0.  , 0.5 , 0.5 , 0.  , 0.25,
       1.  , 0.  , 1.  , 0.  , 1.  , 1.  , 0.  , 0.  , 0.5 , 0.  , 0.5 ,
       1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 0.25, 1.  , 1.  , 1.  ,
       1.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.25, 0.  , 0.5 , 1.  , 0.5 ,
       0.5 , 0.25, 0.5 , 0.  , 0.5 , 0.  , 0.  , 0.5 , 0.  , 1.  , 0.25,
       1.  , 1.  , 1.  , 1.  , 0.25, 0.  , 0.  , 0.  , 0.5 , 1.  , 0.  ,
       0.  , 0.5 , 1.  , 0.25, 0.25, 0.5 , 0.  , 0.  , 0.5 , 0.25, 0.5 ,
       1.  , 1.  , 1.  , 1.  ])

In [26]:
cori_trial_1.time.head(10)

Time Bin 1  Time Bin 2  Time Bin 3  Time Bin 4  Time Bin 5  \
Trial 1    71.207703   71.217703   71.227703   71.237703   71.247703   
Trial 2    81.240263   81.250263   81.260263   81.270263   81.280263   
Trial 3    86.805952   86.815952   86.825952   86.835952   86.845952   
Trial 4    95.989298   95.999298   96.009298   96.019298   96.029298   
Trial 5    99.555755   99.565755   99.575755   99.585755   99.595755   
Trial 6   105.571451  105.581451  105.591451  105.601451  105.611451   
Trial 7   111.071939  111.081939  111.091939  111.101939  111.111939   
Trial 8   115.987617  115.997617  116.007617  116.017617  116.027617   
Trial 9   123.721340  123.731340  123.741340  123.751340  123.761340   
Trial 10  129.737436  129.747436  129.757436  129.767436  129.777436   

          Time Bin 6  Time Bin 7  Time Bin 8  Time Bin 9  Time Bin 10  ...  \
Trial 1    71.257703   71.267703   71.277703   71.287703    71.297703  ...   
Trial 2    81.290263   81.300263   81.310263   81.320263    81.330263  ...   
Trial 3    86.855952   86.865952   86.875952   86.885952    86.895952  ...   
Trial 4    96.039298   96.049298   96.059298   96.069298    96.079298  ...   
Trial 5    99.605755   99.615755   99.625755   99.635755    99.645755  ...   
Trial 6   105.621451  105.631451  105.641451  105.651451   105.661451  ...   
Trial 7   111.121939  111.131939  111.141939  111.151939   111.161939  ...   
Trial 8   116.037617  116.047617  116.057617  116.067617   116.077617  ...   
Trial 9   123.771340  123.781340  123.791340  123.801340   123.811340  ...   
Trial 10  129.787436  129.797436  129.807436  129.817436   129.827436  ...   

          Time Bin 31  Time Bin 32  Time Bin 33  Time Bin 34  Time Bin 35  \
Trial 1     71.507703    71.517703    71.527703    71.537703    71.547703   
Trial 2     81.540263    81.550263    81.560263    81.570263    81.580263   
Trial 3     87.105952    87.115952    87.125952    87.135952    87.145952   
Trial 4     96.289298    96.299298    96.309298    96.319298    96.329298   
Trial 5     99.855755    99.865755    99.875755    99.885755    99.895755   
Trial 6    105.871451   105.881451   105.891451   105.901451   105.911451   
Trial 7    111.371939   111.381939   111.391939   111.401939   111.411939   
Trial 8    116.287617   116.297617   116.307617   116.317617   116.327617   
Trial 9    124.021340   124.031340   124.041340   124.051340   124.061340   
Trial 10   130.037436   130.047436   130.057436   130.067436   130.077436   

          Time Bin 36  Time Bin 37  Time Bin 38  Time Bin 39  Time Bin 40  
Trial 1     71.557703    71.567703    71.577703    71.587703    71.597703  
Trial 2     81.590263    81.600263    81.610263    81.620263    81.630263  
Trial 3     87.155952    87.165952    87.175952    87.185952    87.195952  
Trial 4     96.339298    96.349298    96.359298    96.369298    96.379298  
Trial 5     99.905755    99.915755    99.925755    99.935755    99.945755  
Trial 6    105.921451   105.931451   105.941451   105.951451   105.961451  
Trial 7    111.421939   111.431939   111.441939   111.451939   111.461939  
Trial 8    116.337617   116.347617   116.357617   116.367617   116.377617  
Trial 9    124.071340   124.081340   124.091340   124.101340   124.111340  
Trial 10   130.087436   130.097436   130.107436   130.117436   130.127436  

[10 rows x 40 columns]

In [25]:
cori_trial_1.spikes.get("Trial 1").head(10) # The indices are the neurons

Time Bin 1 Time Bin 2 Time Bin 3 Time Bin 4 Time Bin 5 Time Bin 6  \
ACA         0.0        0.0        0.0        0.0        0.0        0.0   
MOs         0.0        0.0        0.0        0.0        0.0        0.0   
ACA         0.0        0.0        0.0        0.0        0.0        0.0   
LS          0.0        0.0        0.0        0.0        0.0        0.0   
MOs         0.0        0.0        0.0        0.0        0.0        0.0   
ACA         0.0        0.0        1.0        0.0        0.0        0.0   
root        0.0        0.0        0.0        0.0        0.0        0.0   
MOs         0.0        0.0        0.0        0.0        0.0        0.0   
MOs         0.0        0.0        0.0        0.0        0.0        0.0   
LS          0.0        0.0        0.0        0.0        0.0        0.0   

     Time Bin 7 Time Bin 8 Time Bin 9 Time Bin 10  ... Time Bin 31  \
ACA         0.0        0.0        0.0         0.0  ...         0.0   
MOs         0.0        0.0        0.0         0.0  ...         0.0   
ACA         0.0        0.0        0.0         0.0  ...         0.0   
LS          0.0        0.0        0.0         0.0  ...         0.0   
MOs         0.0        0.0        0.0         0.0  ...         0.0   
ACA         1.0        0.0        0.0         0.0  ...         0.0   
root        0.0        0.0        0.0         0.0  ...         0.0   
MOs         0.0        0.0        0.0         0.0  ...         0.0   
MOs         0.0        0.0        0.0         0.0  ...         0.0   
LS          0.0        0.0        0.0         0.0  ...         0.0   

     Time Bin 32 Time Bin 33 Time Bin 34 Time Bin 35 Time Bin 36 Time Bin 37  \
ACA          0.0         0.0         0.0         0.0         0.0         0.0   
MOs          0.0         0.0         0.0         0.0         0.0         0.0   
ACA          0.0         0.0         0.0         0.0         0.0         0.0   
LS           0.0         0.0         0.0         0.0         0.0         0.0   
MOs          0.0         0.0         0.0         0.0         0.0         0.0   
ACA          0.0         0.0         0.0         0.0         0.0         0.0   
root         0.0         0.0         0.0         0.0         0.0         0.0   
MOs          0.0         0.0         0.0         0.0         0.0         0.0   
MOs          0.0         0.0         0.0         0.0         0.0         0.0   
LS           0.0         0.0         0.0         0.0         0.0         0.0   

     Time Bin 38 Time Bin 39 Time Bin 40  
ACA          0.0         0.0         0.0  
MOs          0.0         0.0         0.0  
ACA          0.0         0.0         0.0  
LS           0.0         0.0         0.0  
MOs          0.0         0.0         0.0  
ACA          0.0         0.0         0.0  
root         0.0         0.0         0.0  
MOs          0.0         0.0         0.0  
MOs          0.0         0.0         0.0  
LS           0.0         0.0         0.0  

[10 rows x 40 columns]

## Compare to `Course_project_description.html`

In [2]:
session5 = Mouse(5)

In [43]:
session5.contrast_left

array([0.  , 0.  , 0.25, 0.  , 0.  , 0.5 , 0.  , 0.5 , 0.5 , 0.25, 1.  ,
       0.25, 0.  , 1.  , 1.  , 1.  , 0.5 , 0.5 , 0.25, 0.25, 0.25, 0.  ,
       1.  , 0.5 , 0.  , 0.25, 0.5 , 0.25, 0.25, 0.25, 0.25, 0.5 , 1.  ,
       0.  , 1.  , 1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.25, 0.  , 0.  ,
       0.5 , 0.  , 0.  , 0.  , 0.  , 0.5 , 0.25, 0.  , 0.5 , 0.  , 0.  ,
       1.  , 0.25, 0.25, 0.5 , 0.  , 0.  , 0.  , 0.5 , 0.25, 0.5 , 0.  ,
       0.5 , 1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 1.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.5 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 1.  , 0.  , 1.  , 0.25,
       0.25, 0.  , 0.  , 0.  , 1.  , 0.5 , 0.  , 0.  , 0.25, 0.25, 1.  ,
       0.25, 0.5 , 0.  , 0.  , 0.  , 0.5 , 1.  , 1.  , 0.  , 0.5 , 1.  ,
       0.  , 0.25, 0.  , 0.  , 1.  , 0.  , 0.  , 0.25, 0.  , 0.25, 0.  ,
       0.  , 0.  , 0.25, 0.5 , 0.5 , 0.  , 0.25, 0.  , 0.25, 0.25, 0.  ,
       0.  , 1.  , 1.  , 0.25, 0.25, 0.  , 0.  , 0.

In [29]:
session5.contrast_right

array([1.  , 0.  , 0.25, 0.  , 0.  , 1.  , 0.5 , 1.  , 1.  , 1.  , 0.  ,
       0.5 , 0.25, 1.  , 0.  , 0.25, 0.  , 0.5 , 0.5 , 1.  , 1.  , 1.  ,
       0.  , 0.25, 0.  , 1.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.5 , 1.  ,
       1.  , 0.  , 0.  , 0.5 , 0.  , 0.5 , 0.  , 0.25, 0.5 , 0.  , 0.  ,
       1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.5 , 1.  , 1.  ,
       0.25, 0.25, 1.  , 0.5 , 0.25, 0.  , 0.  , 0.  , 1.  , 1.  , 0.5 ,
       1.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.  ,
       0.25, 0.  , 0.25, 1.  , 0.  , 0.  , 0.5 , 0.  , 0.  , 0.  , 1.  ,
       1.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.25, 0.25, 0.25, 0.  ,
       1.  , 1.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.25, 1.  , 0.25,
       1.  , 1.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 1.  , 0.25, 0.5 ,
       0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.5 ,
       0.  , 0.  , 0.  , 0.25, 1.  , 0.  , 0.  , 0.  , 0.5 , 0.25, 0.  ,
       0.  , 0.25, 0.25, 1.  , 1.  , 1.  , 0.  , 0.

In [ ]:
session5.feedback_type

array([ 1.,  1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,
        1.,  1.,  1.,  1., -1., -1., -1.,  1.,  1.,  1., -1.,  1.,  1.,
        1., -1., -1., -1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1., -1.,  1.,  1.,  1.,  1., -1.,  1.,  1., -1.,  1.,
       -1., -1.,  1.,  1.,  1.,  1., -1., -1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1., -1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1., -1., -1.,  1.,  1.,  1., -1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,
        1., -1.,  1., -1.,  1.,  1.,  1., -1.,  1., -1.,  1.,  1.,  1.,
        1.,  1., -1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1., -1.,  1., -1., -1.,  1.,  1., -1.,  1.,  1.,  1., -1.,
        1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,
        1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1., -1.,  1.,  1., -1., -1., -1., -1.,  1.,  1.,  1

In [36]:
# "There are a total of 1077 neurons in this trial from 10 areas of the brain"

# The (distinct) row labels represent the areas of the brain. The indices are 
# the neurons.

session5.spikes.get("Trial 11")

Time Bin 1 Time Bin 2 Time Bin 3 Time Bin 4 Time Bin 5 Time Bin 6  \
VISa        1.0        0.0        1.0        0.0        0.0        0.0   
VISa        0.0        0.0        0.0        0.0        0.0        0.0   
root        0.0        0.0        0.0        0.0        0.0        0.0   
root        0.0        1.0        0.0        0.0        0.0        0.0   
VISa        0.0        0.0        0.0        0.0        0.0        0.0   
...         ...        ...        ...        ...        ...        ...   
OLF         0.0        0.0        0.0        0.0        0.0        0.0   
OLF         0.0        0.0        0.0        0.0        0.0        0.0   
OLF         0.0        0.0        0.0        0.0        0.0        0.0   
ACA         0.0        0.0        0.0        0.0        0.0        0.0   
ORB         0.0        0.0        0.0        0.0        0.0        0.0   

     Time Bin 7 Time Bin 8 Time Bin 9 Time Bin 10  ... Time Bin 31  \
VISa        0.0        0.0        0.0         0.0  ...         0.0   
VISa        0.0        0.0        0.0         0.0  ...         0.0   
root        0.0        0.0        0.0         0.0  ...         0.0   
root        0.0        0.0        0.0         0.0  ...         0.0   
VISa        0.0        0.0        0.0         0.0  ...         0.0   
...         ...        ...        ...         ...  ...         ...   
OLF         0.0        0.0        0.0         0.0  ...         0.0   
OLF         0.0        0.0        0.0         0.0  ...         0.0   
OLF         0.0        0.0        0.0         0.0  ...         0.0   
ACA         0.0        0.0        0.0         0.0  ...         0.0   
ORB         0.0        0.0        0.0         0.0  ...         0.0   

     Time Bin 32 Time Bin 33 Time Bin 34 Time Bin 35 Time Bin 36 Time Bin 37  \
VISa         0.0         0.0         0.0         0.0         0.0         0.0   
VISa         0.0         0.0         0.0         0.0         0.0         0.0   
root         0.0         0.0         0.0         0.0         0.0         0.0   
root         0.0         0.0         0.0         0.0         0.0         0.0   
VISa         0.0         0.0         0.0         0.0         0.0         0.0   
...          ...         ...         ...         ...         ...         ...   
OLF          0.0         0.0         0.0         0.0         0.0         0.0   
OLF          0.0         0.0         0.0         0.0         0.0         0.0   
OLF          0.0         0.0         0.0         0.0         0.0         0.0   
ACA          0.0         0.0         0.0         0.0         0.0         0.0   
ORB          0.0         0.0         0.0         0.0         0.0         0.0   

     Time Bin 38 Time Bin 39 Time Bin 40  
VISa         0.0         0.0         0.0  
VISa         0.0         0.0         1.0  
root         0.0         0.0         0.0  
root         0.0         0.0         0.0  
VISa         0.0         0.0         0.0  
...          ...         ...         ...  
OLF          0.0         0.0         0.0  
OLF          0.0         0.0         0.0  
OLF          0.0         0.0         0.0  
ACA          0.0         0.0         0.0  
ORB          0.0         0.0         0.0  

[1077 rows x 40 columns]

In [9]:
len(session5.spikes.get("Trial 11").T.columns.unique())

10

In [2]:
session18 = Mouse(18)

In [4]:
# My averages match those in the notes perfectly, but the headers are wrong.
# I cannot for the life of me figure out why this is happening. I have tried
# everything I can think of. Could this be a strange affectation of the import
# process between R and Python?

session18.model_features.head()

Mouse  Session  Trial Decision Feedback       ACB       CA3        CP  \
0  Lederberg       18      1        1      1.0  1.270968  1.628571  1.132911   
1  Lederberg       18      2        1      1.0  1.161290  1.400000  1.120253   
2  Lederberg       18      3        3     -1.0  0.722581  1.428571  0.943038   
3  Lederberg       18      4        3     -1.0  0.890323  0.828571  0.651899   
4  Lederberg       18      5        3      1.0  0.729032  1.257143  0.582278   

        LGd        OT        SI       SNr        TH        ZI      root  
0  0.786517  0.846154  1.854167  0.800000  1.057143  1.125714  2.080808  
1  1.044944  0.576923  2.187500  1.061538  1.411429  1.411429  1.858586  
2  1.247191  0.538462  1.520833  0.923077  1.240000  1.228571  1.919192  
3  1.157303  0.423077  1.812500  0.815385  1.022857  1.182857  1.646465  
4  0.988764  0.346154  1.666667  0.884615  1.360000  1.377143  2.363636