# Exploratory Data Analysis

In [1]:
from scripts.mouse import Mouse

## Structure of the Data

```python
>>> for session in range(1, 19):
>>>     print(f"{session = }: {Mouse(session)}")

session = 1: Cori on 12/14/2016
session = 2: Cori on 12/17/2016
session = 3: Cori on 12/18/2016
session = 4: Forssmann on 11/01/2017
session = 5: Forssmann on 11/02/2017
session = 6: Forssmann on 11/04/2017
session = 7: Forssmann on 11/05/2017
session = 8: Hench on 06/15/2017
session = 9: Hench on 06/16/2017
session = 10: Hench on 06/17/2017
session = 11: Hench on 06/18/2017
session = 12: Lederberg on 12/05/2017
session = 13: Lederberg on 12/06/2017
session = 14: Lederberg on 12/07/2017
session = 15: Lederberg on 12/08/2017
session = 16: Lederberg on 12/09/2017
session = 17: Lederberg on 12/10/2017
session = 18: Lederberg on 12/11/2017
```

In [2]:
# Now we can group the data by mouse

cori = [Mouse(i) for i in range(1, 4)]
forssmann = [Mouse(i) for i in range(4, 8)]
hench = [Mouse(i) for i in range(8, 12)]
lederberg = [Mouse(i) for i in range(12, 19)]

## Testing the Data Pipelines

See `./scripts/open_rds.py` and `./scripts/mouse.py`

In [ ]:
cori_trial_1 = cori[0]

# Test basic string representations

print(cori_trial_1)
print(cori_trial_1.mouse_name)
print(cori_trial_1.date_exp)

Cori on 12/14/2016
Cori
2016-12-14


In [11]:
cori_trial_1.feedback_type

array([0.  , 0.  , 0.5 , 0.  , 0.  , 0.  , 1.  , 0.5 , 0.  , 0.5 , 0.5 ,
       0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.5 , 0.25, 0.  , 1.  ,
       0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.5 , 0.  , 0.  ,
       0.5 , 0.  , 0.  , 0.  , 0.25, 0.  , 1.  , 0.  , 0.  , 1.  , 1.  ,
       0.5 , 1.  , 1.  , 0.  , 0.25, 0.25, 0.5 , 1.  , 0.25, 0.5 , 0.  ,
       0.  , 0.25, 0.25, 0.25, 0.  , 0.  , 0.  , 0.25, 0.25, 0.25, 0.25,
       0.25, 0.  , 0.5 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25,
       0.  , 1.  , 0.25, 0.  , 0.5 , 1.  , 1.  , 0.  , 1.  , 0.  , 0.5 ,
       0.25, 0.25, 0.25, 0.25, 0.5 , 0.5 , 1.  , 0.5 , 0.  , 0.25, 1.  ,
       0.25, 0.5 , 0.5 , 1.  , 1.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.  ,
       0.25, 0.25, 0.25, 0.25])

In [12]:
cori_trial_1.contrast_left

array([0.  , 0.  , 0.5 , 0.  , 0.  , 0.  , 1.  , 0.5 , 0.  , 0.5 , 0.5 ,
       0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.5 , 0.25, 0.  , 1.  ,
       0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.5 , 0.  , 0.  ,
       0.5 , 0.  , 0.  , 0.  , 0.25, 0.  , 1.  , 0.  , 0.  , 1.  , 1.  ,
       0.5 , 1.  , 1.  , 0.  , 0.25, 0.25, 0.5 , 1.  , 0.25, 0.5 , 0.  ,
       0.  , 0.25, 0.25, 0.25, 0.  , 0.  , 0.  , 0.25, 0.25, 0.25, 0.25,
       0.25, 0.  , 0.5 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25,
       0.  , 1.  , 0.25, 0.  , 0.5 , 1.  , 1.  , 0.  , 1.  , 0.  , 0.5 ,
       0.25, 0.25, 0.25, 0.25, 0.5 , 0.5 , 1.  , 0.5 , 0.  , 0.25, 1.  ,
       0.25, 0.5 , 0.5 , 1.  , 1.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.  ,
       0.25, 0.25, 0.25, 0.25])

In [13]:
cori_trial_1.contrast_right

array([0.  , 0.  , 0.5 , 0.  , 0.  , 0.  , 1.  , 0.5 , 0.  , 0.5 , 0.5 ,
       0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.5 , 0.25, 0.  , 1.  ,
       0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.5 , 0.  , 0.  ,
       0.5 , 0.  , 0.  , 0.  , 0.25, 0.  , 1.  , 0.  , 0.  , 1.  , 1.  ,
       0.5 , 1.  , 1.  , 0.  , 0.25, 0.25, 0.5 , 1.  , 0.25, 0.5 , 0.  ,
       0.  , 0.25, 0.25, 0.25, 0.  , 0.  , 0.  , 0.25, 0.25, 0.25, 0.25,
       0.25, 0.  , 0.5 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25,
       0.  , 1.  , 0.25, 0.  , 0.5 , 1.  , 1.  , 0.  , 1.  , 0.  , 0.5 ,
       0.25, 0.25, 0.25, 0.25, 0.5 , 0.5 , 1.  , 0.5 , 0.  , 0.25, 1.  ,
       0.25, 0.5 , 0.5 , 1.  , 1.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.  ,
       0.25, 0.25, 0.25, 0.25])

In [15]:
cori_trial_1.time.head()

Time Bin 1  Time Bin 2  Time Bin 3  Time Bin 4  Time Bin 5  \
Trial 1   71.207703   71.217703   71.227703   71.237703   71.247703   
Trial 2   81.240263   81.250263   81.260263   81.270263   81.280263   
Trial 3   86.805952   86.815952   86.825952   86.835952   86.845952   
Trial 4   95.989298   95.999298   96.009298   96.019298   96.029298   
Trial 5   99.555755   99.565755   99.575755   99.585755   99.595755   

         Time Bin 6  Time Bin 7  Time Bin 8  Time Bin 9  Time Bin 10  ...  \
Trial 1   71.257703   71.267703   71.277703   71.287703    71.297703  ...   
Trial 2   81.290263   81.300263   81.310263   81.320263    81.330263  ...   
Trial 3   86.855952   86.865952   86.875952   86.885952    86.895952  ...   
Trial 4   96.039298   96.049298   96.059298   96.069298    96.079298  ...   
Trial 5   99.605755   99.615755   99.625755   99.635755    99.645755  ...   

         Time Bin 31  Time Bin 32  Time Bin 33  Time Bin 34  Time Bin 35  \
Trial 1    71.507703    71.517703    71.527703    71.537703    71.547703   
Trial 2    81.540263    81.550263    81.560263    81.570263    81.580263   
Trial 3    87.105952    87.115952    87.125952    87.135952    87.145952   
Trial 4    96.289298    96.299298    96.309298    96.319298    96.329298   
Trial 5    99.855755    99.865755    99.875755    99.885755    99.895755   

         Time Bin 36  Time Bin 37  Time Bin 38  Time Bin 39  Time Bin 40  
Trial 1    71.557703    71.567703    71.577703    71.587703    71.597703  
Trial 2    81.590263    81.600263    81.610263    81.620263    81.630263  
Trial 3    87.155952    87.165952    87.175952    87.185952    87.195952  
Trial 4    96.339298    96.349298    96.359298    96.369298    96.379298  
Trial 5    99.905755    99.915755    99.925755    99.935755    99.945755  

[5 rows x 40 columns]

In [18]:
cori_trial_1.spikes.get("Trial 1").head()

Time Bin 1 Time Bin 2 Time Bin 3 Time Bin 4 Time Bin 5 Time Bin 6  \
ACA        0.0        0.0        0.0        0.0        0.0        0.0   
MOs        0.0        0.0        0.0        0.0        0.0        0.0   
ACA        0.0        0.0        0.0        0.0        0.0        0.0   
LS         0.0        0.0        0.0        0.0        0.0        0.0   
MOs        0.0        0.0        0.0        0.0        0.0        0.0   

    Time Bin 7 Time Bin 8 Time Bin 9 Time Bin 10  ... Time Bin 31 Time Bin 32  \
ACA        0.0        0.0        0.0         0.0  ...         0.0         0.0   
MOs        0.0        0.0        0.0         0.0  ...         0.0         0.0   
ACA        0.0        0.0        0.0         0.0  ...         0.0         0.0   
LS         0.0        0.0        0.0         0.0  ...         0.0         0.0   
MOs        0.0        0.0        0.0         0.0  ...         0.0         0.0   

    Time Bin 33 Time Bin 34 Time Bin 35 Time Bin 36 Time Bin 37 Time Bin 38  \
ACA         0.0         0.0         0.0         0.0         0.0         0.0   
MOs         0.0         0.0         0.0         0.0         0.0         0.0   
ACA         0.0         0.0         0.0         0.0         0.0         0.0   
LS          0.0         0.0         0.0         0.0         0.0         0.0   
MOs         0.0         0.0         0.0         0.0         0.0         0.0   

    Time Bin 39 Time Bin 40  
ACA         0.0         0.0  
MOs         0.0         0.0  
ACA         0.0         0.0  
LS          0.0         0.0  
MOs         0.0         0.0  

[5 rows x 40 columns]